version: "3.8"

services:
  node:
    build: ./../docker-node
    volumes:
      - ./../docker-data/contents/:/usr/src/app/public/contents/
    ports:
      - "49161:8080"
    networks:
      - dockleafnet

  redis:
    build: ./../docker-postgis
    volumes:
      - ./../docker-data/:/home/pgis/data/
    networks:
      - dockleafnet

networks:
  dockleafnet:
    driver: bridge