version: "3.8"

services:
  node:
    container_name: arbres-node
    build: ./../docker_node
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://simon:simon@postgis:5432/chenes
    depends_on:
      - postgis
    networks:
      - appnet

  postgis:
    container_name: arbres-postgis
    image: postgis/postgis:16-3.4
    restart: unless-stopped
    environment:
      POSTGRES_USER: simon
      POSTGRES_PASSWORD: simon
      POSTGRES_DB: chenes
    volumes:
      - postgis_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - appnet

  shiny:
    build: ./../docker_shiny
    container_name: arbres-shiny
    ports:
      - "3838:3838"
    depends_on:
      - node
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:
    driver: bridge

volumes:
  postgis_data: